name: Publish Retype generated website to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish to retype branch.

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: mojeeio/mojee-dev
          ssh-key: ${{ secrets.MOJEE_DEV_DEPLOY_KEY }}
          path: mojee-dev-${{ github.run_id }}-${{ github.run_number }}

      - name: move private repo to same level
        shell: bash
        run: mv mojee-dev-${{ github.run_id }}-${{ github.run_number }} ../mojee-dev

      - uses: retypeapp/action-build@next

      - uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true