name: Publish Retype generated website to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish to retype branch.

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: fabriciomurta/mojee-dev
          ssh-key: ${{ secrets.MOJEE_DEV_DEPLOY_KEY }}
          path: ${{ github.workspace }}/../mojee-dev

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - uses: retypeapp/action-build@v1

      - uses: retypeapp/action-github-pages@v1
        with:
          update-branch: true